<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FDG</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="BuiltInAssets\SillyManModel.obj" />
    <None Remove="BuiltInAssets\SillyManTexture.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="BuiltInAssets\SillyManModel.obj" />
    <EmbeddedResource Include="BuiltInAssets\SillyManTexture.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.1" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>

</Project>
